image: gradle:latest

build:
  script:
    - gradle build

test:
  script:
  - gradle test

jar:
  script:
  - gradle jar
  artifacts:
    paths:
    - build/libs/

javadoc:
  script:
  - gradle javadoc